version: 1
validation: sovereign
accounts: 
- name: alice
  coins:
  - 20000token
  - 200000000ubluechip
- name: bob
  coins:
  - 10000token
  - 100000000ubluechip
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 5token
  - 100000ubluechip
validators:
- name: alice
  bonded: 100000000ubluechip
- name: validator1
  bonded: 100000000ubluechip
- name: validator2
  bonded: 200000000ubluechip
- name: validator3
  bonded: 300000000ubluechip
consensus:
  timeout_commit: "6s"
genesis:
  app_state:
    mint:
      params:
        mint_denom: "ubluechip"
        inflation_rate_change: "0.000000000000000000"
        inflation_max: "0.000000000000000000"
        inflation_min: "0.000000000000000000"
    staking:
      params:
        bond_denom: "ubluechip"
    crisis:
      constant_fee:
        denom: "ubluechip"
    gov:
      params:
        min_deposit:
        - amount: "10000000"
          denom: "ubluechip"
    ibc:
      client_genesis:
        params:
          allowed_clients:
          - "07-tendermint"
          - "06-solomachine"

